#!/bin/bash
# nohup
#python src/classify.py 
#python src/main.py -t -hdf5 -l -batch_stat -metrics is fid prdc -ref "valid" -data /mnt/data/datasets/rwth/ -cfg ./src/configs/RWTH/SPADE.yaml -save ./samples/RWTH/SPADE/ --is_ref_dataset --project titan-skeleton --num_workers 4 -every 500 --pose --skeleton > ./logs/RWTH/SPADE/run0.out 2> ./logs/RWTH/SPADE/run0.err
#python src/main.py -t -hdf5 -l -batch_stat -metrics is fid prdc -ref "valid" -data /mnt/sda2/datasets/rwth/ -cfg ./src/configs/RWTH/SPADE-ReACGAN.yaml -save ./samples/RWTH/SPADE-ReACGAN/ --is_ref_dataset --project titan-skeleton --num_workers 4 -every 500 --pose --skeleton > ./logs/RWTH/SPADE-ReACGAN/run0.out 2> ./logs/RWTH/SPADE-ReACGAN/run0.err
#python src/main.py -t -hdf5 -l -batch_stat -metrics is fid prdc -ref "valid" -data /mnt/sda2/datasets/rwth/ -cfg ./src/configs/RWTH/ReACGAN-ADC-DiffAug.yaml -save ./samples/RWTH/ReACGAN-ADC-DiffAug/ --is_ref_dataset --project titan-skeleton --num_workers 4 -every 500 > ./logs/RWTH/ReACGAN-ADC-DiffAug/run0.out 2> ./logs/RWTH/ReACGAN-ADC-DiffAug/run0.err
#python src/main.py -sd -sd_num 1000 -ref "valid" -data /mnt/sda2/datasets/rwth -cfg ./src/configs/RWTH/SPADE.yaml -save ./samples/RWTH/SPADE-skeleton/ -ckpt ./samples/RWTH/SPADE/checkpoints/RWTH-SPADE-train-2022_08_07_22_50_49/ --num_workers 4 --pose --skeleton > ./logs/RWTH/SPADE/sf0.out 2> ./logs/RWTH/SPADE/sf0.err
#python src/main.py -sd -sd_num 1000 -ref "valid" -data /mnt/sda2/datasets/rwth -cfg ./src/configs/RWTH/SPADE-ReACGAN.yaml -save ./samples/RWTH/SPADE-ReACGAN-skeleton/ -ckpt ./samples/RWTH/SPADE-ReACGAN/checkpoints/RWTH-SPADE-ReACGAN-train-2022_06_16_06_50_26/ --num_workers 4 --truncation_factor 0.5 --pose > ./logs/RWTH/SPADE-ReACGAN/sf0.out 2> ./logs/RWTH/SPADE-ReACGAN/sf0.err
#python src/main.py -sd -sd_num 1000 -ref "valid" -data /mnt/sda2/datasets/rwth -cfg ./src/configs/RWTH/ReACGAN-ADC-DiffAug.yaml -save ./samples/RWTH/ReACGAN-ADC-DiffAug/ -ckpt ./samples/RWTH/ReACGAN-ADC-DiffAug/checkpoints/RWTH-ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29/ --num_workers 4 > ./logs/RWTH/ReACGAN-ADC-DiffAug/sf0.out 2> ./logs/RWTH/ReACGAN-ADC-DiffAug/sf0.err


#python src/classify.py --train_mode mixgen --dset1 /mnt/sda2/datasets/rwth --dset2 /mnt/sda2/datasets/rwth-ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29 -save ./classifier_results/gen/rwth-ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29/ --num_workers 4 --epochs 200 --batch_size 128
#python src/classify.py --train_mode reggen --dset1 /mnt/sda2/datasets/rwth --dset2 /mnt/sda2/datasets/rwth-ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29 -save ./classifier_results/gen/rwth-ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29/ --num_workers 4 --epochs 200 --batch_size 128
#python src/classify.py --train_mode real --dset1 /mnt/sda2/datasets/rwth --batch_size 256 -save ./classifier_results/real/rwth/ -sm --num_workers 4 --epochs 200
#python src/classify.py --train_mode gen --dset1 /mnt/sda2/datasets/rwth --dset2 /mnt/sda2/datasets/ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29 --batch_size 256 -save ./classifier_results/gen/rwth-ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29/ --num_workers 4 --epochs 200
#python src/classify.py --train_mode mixgen --dset1 /mnt/sda2/datasets/rwth --dset2 /mnt/sda2/datasets/ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29 --batch_size 128 -save ./classifier_results/gen/rwth-ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29/ --num_workers 4 --epochs 200
#python src/classify.py --train_mode reggen --dset1 /mnt/sda2/datasets/rwth --dset2 /mnt/sda2/datasets/ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29 --batch_size 128 -save ./classifier_results/gen/rwth-ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29/ --num_workers 4 --epochs 200


# Filter top k samples
#python src/classify.py --top_k 100 -lm ./classifier_results/real/rwth/model_state_dict.pt --dset1 /mnt/sda2/datasets/rwth --dset2 /mnt/sda2/datasets/ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29 --batch_size 128 -save ./classifier_results/real/rwth/ --num_workers 4
#python src/classify.py --train_mode reggen --dset1 /mnt/sda2/datasets/rwth --dset2 ./classifier_results/real/rwth/ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29 --batch_size 128 -save ./classifier_results/gen/filtered-rwth-ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29/ --num_workers 4 --epochs 200
#python src/classify.py --train_mode mixgen --dset1 /mnt/sda2/datasets/rwth --dset2 ./classifier_results/real/rwth/ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29 --batch_size 128 -save ./classifier_results/gen/filtered-rwth-ReACGAN-ADC-DiffAug-train-2022_09_02_12_25_29/ --num_workers 4 --epochs 200
