#!/bin/bash
# nohup

# Save dataset Hagrid
#echo "--Save Hagrid ReACGAN 10 generated dataset--"
#python src/main.py -sd -sd_num 1000 -ref "valid" -data /mnt/sda2/datasets/static-sl/hagrid-complete/ -cfg ./src/configs/hagrid-complete/ReACGAN-ADC-DiffAug-10.yaml -save /mnt/sda2/datasets/static-sl/hagrid-complete/ReACGAN-ADC-DiffAug-10/ -ckpt /mnt/sda2/old_home/grios/TDGsamples/hagrid-complete/ReACGAN-ADC-DiffAug-10/checkpoints/hagrid-complete-ReACGAN-ADC-DiffAug-10-train-2023_04_26_01_35_42/ -best --num_workers 4 --truncation_factor 0.5 > ./logs/hagrid-complete/ReACGAN-ADC-DiffAug-10/sf0.out 2> ./logs/hagrid-complete/ReACGAN-ADC-DiffAug-10/sf0.err
#mv /mnt/sda2/datasets/static-sl/hagrid-complete/ReACGAN-ADC-DiffAug-10/samples/ReACGAN-ADC-DiffAug-10-train-2023_04_26_01_35_42/fake/ /mnt/sda2/datasets/static-sl/hagrid-complete/ReACGAN-ADC-DiffAug-10/samples/ReACGAN-ADC-DiffAug-10-train-2023_04_26_01_35_42/train/
#echo "--Save Hagrid ReACGAN 20 generated dataset--"
#python src/main.py -sd -sd_num 1000 -ref "valid" -data /mnt/sda2/datasets/static-sl/hagrid-complete/ -cfg ./src/configs/hagrid-complete/ReACGAN-ADC-DiffAug-20.yaml -save /mnt/sda2/datasets/static-sl/hagrid-complete/ReACGAN-ADC-DiffAug-20/ -ckpt /mnt/sda2/old_home/grios/TDGsamples/hagrid-complete/ReACGAN-ADC-DiffAug-20/checkpoints/hagrid-complete-ReACGAN-ADC-DiffAug-20-train-2023_04_26_03_38_48/ -best --num_workers 4 --truncation_factor 0.5 > ./logs/hagrid-complete/ReACGAN-ADC-DiffAug-20/sf0.out 2> ./logs/hagrid-complete/ReACGAN-ADC-DiffAug-20/sf0.err
#mv /mnt/sda2/datasets/static-sl/hagrid-complete/ReACGAN-ADC-DiffAug-20/samples/ReACGAN-ADC-DiffAug-20-train-2023_04_26_03_38_48/fake/ /mnt/sda2/datasets/static-sl/hagrid-complete/ReACGAN-ADC-DiffAug-20/samples/ReACGAN-ADC-DiffAug-20-train-2023_04_26_03_38_48/train/
#echo "--Save Hagrid ReACGAN 40 generated dataset--"
#python src/main.py -sd -sd_num 1000 -ref "valid" -data /mnt/sda2/datasets/static-sl/hagrid-complete/ -cfg ./src/configs/hagrid-complete/ReACGAN-ADC-DiffAug-40.yaml -save /mnt/sda2/datasets/static-sl/hagrid-complete/ReACGAN-ADC-DiffAug-40/ -ckpt /mnt/sda2/old_home/grios/TDGsamples/hagrid-complete/ReACGAN-ADC-DiffAug-40/checkpoints/hagrid-complete-ReACGAN-ADC-DiffAug-40-train-2023_04_26_06_18_58/ -best --num_workers 4 --truncation_factor 0.5 > ./logs/hagrid-complete/ReACGAN-ADC-DiffAug-40/sf0.out 2> ./logs/hagrid-complete/ReACGAN-ADC-DiffAug-40/sf0.err
#mv /mnt/sda2/datasets/static-sl/hagrid-complete/ReACGAN-ADC-DiffAug-40/samples/ReACGAN-ADC-DiffAug-40-train-2023_04_26_06_18_58/fake/ /mnt/sda2/datasets/static-sl/hagrid-complete/ReACGAN-ADC-DiffAug-40/samples/ReACGAN-ADC-DiffAug-40-train-2023_04_26_06_18_58/train/

# Save dataset RWTH-small
#echo "--Save RWTH-small ReACGAN 5 generated dataset--"
#python src/main.py -sd -sd_num 1000 -ref "valid" -data /mnt/sda2/datasets/static-sl/rwth-small -cfg ./src/configs/RWTH-small/ReACGAN-ADC-DiffAug-highcond-5.yaml -save /mnt/sda2/datasets/static-sl/rwth-smallReACGAN-ADC-DiffAug-highcond-5/ -ckpt /mnt/sda2/old_home/grios/TDGsamples/RWTH-small/ReACGAN-ADC-DiffAug-highcond-5/checkpoints/RWTH-ReACGAN-ADC-DiffAug-highcond-5-train-2023_04_26_10_15_16/ -best --num_workers 4 --truncation_factor 0.5 > ./logs/RWTH-small/ReACGAN-ADC-DiffAug-highcond-5/sf0.out 2> ./logs/RWTH-small/ReACGAN-ADC-DiffAug-highcond-5/sf0.err
#mv /mnt/sda2/datasets/RWTH-small/ReACGAN-ADC-DiffAug-highcond-5/samples/ReACGAN-ADC-DiffAug-highcond-5-train-2023_04_26_10_15_16/fake/ /mnt/sda2/datasets/RWTH-small/ReACGAN-ADC-DiffAug-highcond-5/samples/ReACGAN-ADC-DiffAug-highcond-5-train-2023_04_26_10_15_16/train/
#echo "--Save RWTH-small ReACGAN 10 generated dataset--"
#python src/main.py -sd -sd_num 1000 -ref "valid" -data /mnt/sda2/datasets/rwth-small/ -cfg ./src/configs/RWTH-small/ReACGAN-ADC-DiffAug-highcond-10.yaml -save /mnt/sda2/datasets/RWTH-small/ReACGAN-ADC-DiffAug-highcond-10/ -ckpt /mnt/sda2/old_home/grios/TDGsamples/RWTH-small/ReACGAN-ADC-DiffAug-highcond-10/checkpoints/RWTH-ReACGAN-ADC-DiffAug-highcond-10-train-2023_04_26_14_40_45/ -best --num_workers 4 --truncation_factor 0.5 > ./logs/RWTH-small/ReACGAN-ADC-DiffAug-highcond-10/sf0.out 2> ./logs/RWTH-small/ReACGAN-ADC-DiffAug-highcond-10/sf0.err
#mv /mnt/sda2/datasets/RWTH-small/ReACGAN-ADC-DiffAug-highcond-10/samples/ReACGAN-ADC-DiffAug-highcond-10-train-2023_04_26_14_40_45/fake/ /mnt/sda2/datasets/RWTH-small/ReACGAN-ADC-DiffAug-highcond-10/samples/ReACGAN-ADC-DiffAug-highcond-10-train-2023_04_26_14_40_45/train/
#echo "--Save RWTH-small ReACGAN 20 generated dataset--"
#python src/main.py -sd -sd_num 1000 -ref "valid" -data /mnt/sda2/datasets/rwth-small/ -cfg ./src/configs/RWTH-small/ReACGAN-ADC-DiffAug-highcond-20.yaml -save /mnt/sda2/datasets/RWTH-small/ReACGAN-ADC-DiffAug-highcond-20/ -ckpt /mnt/sda2/old_home/grios/TDGsamples/RWTH-small/ReACGAN-ADC-DiffAug-highcond-20/checkpoints/RWTH-ReACGAN-ADC-DiffAug-highcond-20-train-2023_04_26_16_56_53/ -best --num_workers 4 --truncation_factor 0.5 > ./logs/RWTH-small/ReACGAN-ADC-DiffAug-highcond-20/sf0.out 2> ./logs/RWTH-small/ReACGAN-ADC-DiffAug-highcond-20/sf0.err
#mv /mnt/sda2/datasets/RWTH-small/ReACGAN-ADC-DiffAug-highcond-20/samples/ReACGAN-ADC-DiffAug-highcond-20-train-2023_04_26_16_56_53/fake/ /mnt/sda2/datasets/RWTH-small/ReACGAN-ADC-DiffAug-highcond-20/samples/ReACGAN-ADC-DiffAug-highcond-20-train-2023_04_26_16_56_53/train/

echo "--Hagrid-10 real--"
python src/classify.py --train_mode real --dset1 /mnt/sda2/datasets/static-sl/hagrid-complete/ --batch_size 8 -save /mnt/sda2/models/TDG/classifier_results/real/hagrid-nopretrain-10/ --num_workers 4 --epochs 100 --n_classes 18 --dims 64 --dset_used 180
echo "--Hagrid-20 real--"
python src/classify.py --train_mode real --dset1 /mnt/sda2/datasets/static-sl/hagrid-complete/ --batch_size 16 -save /mnt/sda2/models/TDG/classifier_results/real/hagrid-nopretrain-20/ --num_workers 4 --epochs 100 --n_classes 18 --dims 64 --dset_used 360
echo "--Hagrid-40 real--"
python src/classify.py --train_mode real --dset1 /mnt/sda2/datasets/static-sl/hagrid-complete/ --batch_size 32 -save /mnt/sda2/models/TDG/classifier_results/real/hagrid-nopretrain-40/ --num_workers 4 --epochs 100 --n_classes 18 --dims 64 --dset_used 720
#echo "--Hagrid-10 gen--"
#python src/classify.py --train_mode gen --dset1 /mnt/sda2/datasets/static-sl/hagrid-complete/ --dset2 /mnt/sda2/datasets/generated/hagrid-complete-SPADE-train-2023_06_09_14_37_21/ --batch_size 8 -save /mnt/sda2/models/TDG/classifier_results/gen/hagrid-complete-SPADE-10/ --num_workers 4 --epochs 100 --n_classes 18 --dims 64 --dset_used 180
#echo "--Hagrid-10 mixgen--"
#python src/classify.py --train_mode mixgen --dset1 /mnt/sda2/datasets/static-sl/hagrid-complete/ --dset2 /mnt/sda2/datasets/generated/hagrid-complete-SPADE-train-2023_06_09_14_37_21/ --batch_size 8 -save /mnt/sda2/models/TDG/classifier_results/mixgen/hagrid-complete-SPADE-10/ --num_workers 4 --epochs 100 --n_classes 18 --dims 64 --reg_alpha 0. --reg_beta 0.04 --growth --dset_used 180
#echo "--Hagrid-10 reggen--"
#python src/classify.py --train_mode reggen --dset1 /mnt/sda2/datasets/static-sl/hagrid-complete/ --dset2 /mnt/sda2/datasets/generated/hagrid-complete-SPADE-train-2023_06_09_14_37_21/ --batch_size 8 -save /mnt/sda2/models/TDG/classifier_results/regen/hagrid-complete-SPADE-10/ --num_workers 4 --epochs 100 --n_classes 18 --dims 64 --reg_alpha 0.5 --reg_beta 0.04 --dset_used 180
#echo "--Hagrid-20 gen--"
#python src/classify.py --train_mode gen --dset1 /mnt/sda2/datasets/static-sl/hagrid-complete/ --dset2 /mnt/sda2/datasets/generated/hagrid-complete-SPADE-train-2023_06_09_14_37_21/ --batch_size 16 -save /mnt/sda2/models/TDG/classifier_results/gen/hagrid-complete-SPADE-20/ --num_workers 4 --epochs 100 --n_classes 18 --dims 64 --dset_used 360
#echo "--Hagrid-20 mixgen--"
#python src/classify.py --train_mode mixgen --dset1 /mnt/sda2/datasets/static-sl/hagrid-complete/ --dset2 /mnt/sda2/datasets/generated/hagrid-complete-SPADE-train-2023_06_09_14_37_21/ --batch_size 16 -save /mnt/sda2/models/TDG/classifier_results/mixgen/hagrid-complete-SPADE-20/ --num_workers 4 --epochs 100 --n_classes 18 --dims 64 --reg_alpha 0. --reg_beta 0.04 --growth --dset_used 360
#echo "--Hagrid-20 reggen--"
#python src/classify.py --train_mode reggen --dset1 /mnt/sda2/datasets/static-sl/hagrid-complete/ --dset2 /mnt/sda2/datasets/generated/hagrid-complete-SPADE-train-2023_06_09_14_37_21/ --batch_size 16 -save /mnt/sda2/models/TDG/classifier_results/regen/hagrid-complete-SPADE-20/ --num_workers 4 --epochs 100 --n_classes 18 --dims 64 --reg_alpha 0.5 --reg_beta 0.04 --dset_used 360
#echo "--Hagrid-40 gen--"
#python src/classify.py --train_mode gen --dset1 /mnt/sda2/datasets/static-sl/hagrid-complete/ --dset2 /mnt/sda2/datasets/generated/hagrid-complete-SPADE-train-2023_06_09_14_37_21/ --batch_size 32 -save /mnt/sda2/models/TDG/classifier_results/gen/hagrid-complete-SPADE-40/ --num_workers 4 --epochs 100 --n_classes 18 --dims 64 --dset_used 720
#echo "--Hagrid-40 mixgen--"
#python src/classify.py --train_mode mixgen --dset1 /mnt/sda2/datasets/static-sl/hagrid-complete/ --dset2 /mnt/sda2/datasets/generated/hagrid-complete-SPADE-train-2023_06_09_14_37_21/ --batch_size 32 -save /mnt/sda2/models/TDG/classifier_results/mixgen/hagrid-complete-SPADE-40/ --num_workers 4 --epochs 100 --n_classes 18 --dims 64 --reg_alpha 0. --reg_beta 0.04 --growth --dset_used 720
#echo "--Hagrid-40 reggen--"
#python src/classify.py --train_mode reggen --dset1 /mnt/sda2/datasets/static-sl/hagrid-complete/ --dset2 /mnt/sda2/datasets/generated/hagrid-complete-SPADE-train-2023_06_09_14_37_21/ --batch_size 32 -save /mnt/sda2/models/TDG/classifier_results/regen/hagrid-complete-SPADE-40/ --num_workers 4 --epochs 100 --n_classes 18 --dims 64 --reg_alpha 0.5 --reg_beta 0.04 --dset_used 720

#echo "--RWTH-small-5 real--"
#python src/classify.py --train_mode real --dset1 /mnt/sda2/datasets/static-sl/rwth-small --batch_size 4 -save /mnt/sda2/models/TDG/classifier_results/real/rwth-small-nopretrain-5/ --num_workers 4 --epochs 100 --n_classes 13 --dims 64 --dset_used 65
#echo "--RWTH-small-10 real--"
#python src/classify.py --train_mode real --dset1 /mnt/sda2/datasets/static-sl/rwth-small --batch_size 8 -save /mnt/sda2/models/TDG/classifier_results/real/rwth-small-nopretrain-10/ --num_workers 4 --epochs 100 --n_classes 13 --dims 64 --dset_used 130
#echo "--RWTH-small-20 real--"
#python src/classify.py --train_mode real --dset1 /mnt/sda2/datasets/static-sl/rwth-small --batch_size 16 -save /mnt/sda2/models/TDG/classifier_results/real/rwth-small-nopretrain-20/ --num_workers 4 --epochs 100 --n_classes 13 --dims 64 --dset_used 260
#echo "--RWTH-small-5 gen--"
#python src/classify.py --train_mode gen --dset1 /mnt/sda2/datasets/static-sl/rwth-small/ --dset2 /mnt/sda2/datasets/generated/rwth-small-SPADE-train-2022_06_27_16_44_03/ --batch_size 4 -save /mnt/sda2/models/TDG/classifier_results/gen/RWTH-small-SPADE-5/ --num_workers 4 --epochs 100 --n_classes 13 --dims 64 --dset_used 65
#echo "--RWTH-small-5 mixgen--"
#python src/classify.py --train_mode mixgen --dset1 /mnt/sda2/datasets/static-sl/rwth-small --dset2 /mnt/sda2/datasets/generated/rwth-small-SPADE-train-2022_06_27_16_44_03/ --batch_size 4 -save /mnt/sda2/models/TDG/classifier_results/mixgen/RWTH-small-SPADE-5/ --num_workers 4 --epochs 100 --n_classes 13 --dims 64 --reg_alpha 0. --reg_beta 0.04 --growth --dset_used 65
#echo "--RWTH-small-5 reggen--"
#python src/classify.py --train_mode reggen --dset1 /mnt/sda2/datasets/static-sl/rwth-small --dset2 /mnt/sda2/datasets/generated/rwth-small-SPADE-train-2022_06_27_16_44_03/ --batch_size 4 -save /mnt/sda2/models/TDG/classifier_results/regen/RWTH-small-SPADE-5/ --num_workers 4 --epochs 100 --n_classes 13 --dims 64 --reg_alpha 0.5 --reg_beta 0.04 --dset_used 65
#echo "--RWTH-small-10 gen--"
#python src/classify.py --train_mode gen --dset1 /mnt/sda2/datasets/static-sl/rwth-small --dset2 /mnt/sda2/datasets/generated/rwth-small-SPADE-train-2022_06_27_16_44_03/ --batch_size 8 -save /mnt/sda2/models/TDG/classifier_results/gen/RWTH-small-SPADE-10/ --num_workers 4 --epochs 100 --n_classes 13 --dims 64 --dset_used 130
#echo "--RWTH-small-10 mixgen--"
#python src/classify.py --train_mode mixgen --dset1 /mnt/sda2/datasets/static-sl/rwth-small --dset2 /mnt/sda2/datasets/generated/rwth-small-SPADE-train-2022_06_27_16_44_03/ --batch_size 8 -save /mnt/sda2/models/TDG/classifier_results/mixgen/RWTH-small-SPADE-10/ --num_workers 4 --epochs 100 --n_classes 13 --dims 64 --reg_alpha 0. --reg_beta 0.04 --growth --dset_used 130
#echo "--RWTH-small-10 reggen--"
#python src/classify.py --train_mode reggen --dset1 /mnt/sda2/datasets/static-sl/rwth-small --dset2 /mnt/sda2/datasets/generated/rwth-small-SPADE-train-2022_06_27_16_44_03/ --batch_size 8 -save /mnt/sda2/models/TDG/classifier_results/regen/RWTH-small-SPADE-10/ --num_workers 4 --epochs 100 --n_classes 13 --dims 64 --reg_alpha 0.5 --reg_beta 0.04 --dset_used 130
#echo "--RWTH-small-20 gen--"
#python src/classify.py --train_mode gen --dset1 /mnt/sda2/datasets/static-sl/rwth-small --dset2 /mnt/sda2/datasets/generated/rwth-small-SPADE-train-2022_06_27_16_44_03/ --batch_size 16 -save /mnt/sda2/models/TDG/classifier_results/gen/RWTH-small-SPADE-20/ --num_workers 4 --epochs 100 --n_classes 13 --dims 64 --dset_used 260
#echo "--RWTH-small-20 mixgen--"
#python src/classify.py --train_mode mixgen --dset1 /mnt/sda2/datasets/static-sl/rwth-small --dset2 /mnt/sda2/datasets/generated/rwth-small-SPADE-train-2022_06_27_16_44_03/ --batch_size 16 -save /mnt/sda2/models/TDG/classifier_results/mixgen/RWTH-small-SPADE-20/ --num_workers 4 --epochs 100 --n_classes 13 --dims 64 --reg_alpha 0. --reg_beta 0.04 --growth --dset_used 260
#echo "--RWTH-small-20 reggen--"
#python src/classify.py --train_mode reggen --dset1 /mnt/sda2/datasets/static-sl/rwth-small --dset2 /mnt/sda2/datasets/generated/rwth-small-SPADE-train-2022_06_27_16_44_03/ --batch_size 16 -save /mnt/sda2/models/TDG/classifier_results/regen/RWTH-small-SPADE-20/ --num_workers 4 --epochs 100 --n_classes 13 --dims 64 --reg_alpha 0.5 --reg_beta 0.04 --dset_used 260